In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, log_loss

# Generate synthetic data
X = np.random.rand(1000, 10)  # 1000 samples, 10 features
y = np.random.randint(2, size=1000)  # Binary target

In [3]:
print(X)

[[0.26265915 0.93582286 0.29439288 ... 0.98891027 0.75050446 0.96841363]
 [0.75363651 0.68007926 0.13725306 ... 0.23635249 0.93241572 0.24765339]
 [0.63444439 0.52413597 0.59196696 ... 0.81422871 0.81145474 0.14140727]
 ...
 [0.18352255 0.30322767 0.72158001 ... 0.53145485 0.56557502 0.25861335]
 [0.55227191 0.5534319  0.33070602 ... 0.06719155 0.89548342 0.59802575]
 [0.05256628 0.23629633 0.75726907 ... 0.36334036 0.88705506 0.51967669]]


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
model = MLPClassifier(hidden_layer_sizes=(64,), activation='relu', solver='adam', max_iter=10, batch_size=32, random_state=42)

In [8]:
model.fit(X_train, y_train)

C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(batch_size=32, hidden_layer_sizes=(64,), max_iter=10,
              random_state=42)

In [10]:
y_pred=model.predict(X_test)

In [14]:
y_pred_proba = model.predict_proba(X_test)[:, 1]

accuracy = accuracy_score(y_test, y_pred)
loss = log_loss(y_test, y_pred_proba)

In [15]:
print(f"Loss: {loss}, Accuracy: {accuracy}")

Loss: 0.6959928793653617, Accuracy: 0.445
